#!{{pkgPathFor "core/bash"}}/bin/bash

set -e
exec 2>&1

export FARSPARK_KEY={{ cfg.signature.key }}
export FARSPARK_SALT={{ cfg.signature.salt }}
export FARSPARK_BIND={{ cfg.server.bind }}
export FARSPARK_READ_TIMEOUT={{ cfg.server.read_timeout }}
export FARSPARK_WRITE_TIMEOUT={{ cfg.server.write_timeout }}
export FARSPARK_DOWNLOAD_TIMEOUT={{ cfg.server.download_timeout }}
export FARSPARK_CONCURRENCY={{ cfg.server.concurrency }}
export FARSPARK_MAX_CLIENTS={{ cfg.server.max_client }}
export FARSPARK_TTL={{ cfg.server.ttl }}
export FARSPARK_USE_ETAG={{ cfg.server.use_etag }}
export FARSPARK_LOCAL_FILESYSTEM_ROOT={{ cfg.server.local_filesystem_root }}
export FARSPARK_MAX_SRC_DIMENSION={{ cfg.security.max_src_dimension  }}
export FARSPARK_MAX_SRC_RESOLUTION={{ cfg.security.max_src_resolution }}
export FARSPARK_QUALITY={{ cfg.compression.quality }}
export FARSPARK_GZIP_COMPRESSION={{ cfg.compression.gzip_compression }}
export FARSPARK_SECRET={{ cfg.security.secret }}
export FARSPARK_ALLOW_ORIGINS={{ cfg.security.allow_origins }}
export FARSPARK_BASE_URL={{ cfg.misc.base_url }}
export FARSPARK_CACHE_SIZE={{ cfg.misc.cache_size }}

{{ #if cfg.misc.cache_root }}
export FARSPARK_CACHE_ROOT={{ cfg.misc.cache_root }}
{{ else }}
export FARSPARK_CACHE_ROOT={{ pkg.svc_var_path }}
{{ /if }}

exec farspark
